---

- debug: var=ansible_os_family

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}-{{ ansible_lsb.codename }}.yml"
  - "Debian-default.yml"
  when: ansible_os_family == 'Debian' and collectd_service_autodetect

- import_tasks: install.ppa.yml
  when: collectd_use_ppa
  tags: [collectd, collectd-install]

- import_tasks: install.deb.yml
  when: not collectd_use_ppa and ansible_os_family == 'Debian'
  tags: [collectd, collectd-install]

- import_tasks: configure.yml
  tags: [collectd, collectd-configure]

- import_tasks: configure-service.yml
  when: not collectd_use_ppa
  tags: [collectd, collectd-configure]
